#!/bin/sh
#
# /etc/rc.d/winbindd: start/stop winbindd
#

SSD=/sbin/start-stop-daemon
WINBIND=/usr/sbin/winbindd
WINBIND_PID=/var/run/samba/winbindd.pid


print_status() {
    $SSD --status --pidfile $2
    case $? in
        0) echo "$1 is running with pid $(cat $2)" ;;
        1) echo "$1 is not running but the pid file $2 exists" ;;
        3) echo "$1 is not running" ;;
        4) echo "Unable to determine the program status" ;;
    esac
}

case $1 in
    start)
        $SSD --start --pidfile $WINBIND_PID --exec $WINBIND -- -D
        ;;
    stop)
        $SSD --stop --retry 10 --pidfile $WINBIND_PID 
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    reload)
        /usr/bin/smbcontrol winbindd reload-config
        ;;
    status)
        print_status $WINBIND $WINBIND_PID
        ;;
    *)
        echo "usage: $0 [start|stop|restart|reload|status]"
        ;;
esac

# End of file
